version: '3'
services:
  mega_backup:
    build: .
    image: mega_backup
    container_name: mega_backup
    hostname: mega_backup
    env_file: mega.env
    restart: always
    volumes:
      - .:/usr/src/app
    command: bash -c 'python -u mega_sql_script.py -u 0 -s 2'
  mega_backup_1:
    image: mega_backup
    container_name: mega_backup_1
    hostname: mega_backup_1
    env_file: mega.env
    restart: always
    volumes:
      - .:/usr/src/app
    command: bash -c 'python -u mega_sql_script.py -u 1 -s 2'
  mega_backup_split:
    image: mega_backup
    container_name: mega_backup_split
    hostname: mega_backup_split
    env_file: mega.env
    restart: always
    volumes:
      - .:/usr/src/app
    command: bash -c 'python -u mega_sql_script.py -l 0'
  # mega_backup_check_expired:
  #   image: mega_backup
  #   container_name: mega_backup_check_expired
  #   hostname: mega_backup_check_expired
  #   env_file: mega.env
  #   restart: always
  #   volumes:
  #     - .:/usr/src/app
  #   command: bash -c 'python -u mega_sql_script.py -l 2'

